version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_HOST: localhost
      MYSQL_USER: django
      MYSQL_PASSWORD: django
    ports:
      - "3306:3306"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ether

  ether:
    build: './etherpad'
    entrypoint: sh /entrypoint.sh
    command: sh bin/run.sh --root
    environment:
      ETHERPAD_DB_HOST: db
      ETHERPAD_DB_PASSWORD: root
      ETHERPAD_API_KEY: c1f3ae385ed34c9571261c2a439248843e792ae43fefdec6ace2bb6eb80ac65b
      ETHERPAD_DB_NAME: blog
    ports:
      - "9001:9001"
    depends_on:
      - db
