# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-22 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190219_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
