# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 08:59
from __future__ import unicode_literals

import Media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediatype', models.CharField(choices=[('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video')], default='IMAGE', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('mediafile', models.FileField(null=True, upload_to=Media.models.get_file_path)),
                ('medialink', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Publish', 'Publish')], default='Draft', max_length=50)),
            ],
        ),
    ]
