# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0003_auto_20190305_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='status',
        ),
    ]
